as yet unclassified
testLongArticle
	"self debug: #testLongArticle"

	super testLongArticle.
	self assert: result = 'Hani Abdeen, Ilham Alloui, St\''ephane Ducasse, Damien Pollet, and Mathieu Suen. Package Reference Fingerprint: a Rich and Compact Visualization to Understand Package Relationships. In European Conference on Software Maintenance and Reengineering (CSMR), p. 213--222, IEEE Computer Society Press, 2008. Acceptance rate: 24/87 = 28%.

' 