examples for tests
Abde08a
	"self  Abde08a"
^
(CZBibParser parse: 
'
@inproceedings{Abde08a,
author = {Hani Abdeen and Ilham Alloui and St\''ephane Ducasse and Damien Pollet and Mathieu Suen},
title = {Package Reference Fingerprint: a Rich and Compact Visualization to Understand Package Relationships},
booktitle = {European Conference on Software Maintenance and Reengineering (CSMR)},
pages = {213--222},
publisher = {IEEE Computer Society Press},
year = 2008,
acceptnum = {24},
accepttotal = {87}
}

'
)  