examples for tests
Lanz02b
	"self Lanz02b"
^
(CZBibParser parse: 
'

@inproceedings{Lanz02b,
  author = {Michele Lanza and St\''ephane Ducasse},
  title = {Beyond Language Independent Object-Oriented Metrics: Model Independent Metrics},
  booktitle = {Proceedings of the 6th International Workshop on Quantitative Approaches in Object-Oriented Software Engineering},
  pages = {77--84},
  year = {2002},
  url = {http://rmod.inria.fr/archives/papers/Lanz02bModelIndependentMetrics.pdf},
  abstract = {Software Metrics have become essential in software
 engineering for several reasons, among which quality
 assessment and reengineering. In the context of the
 European Esprit Project FAMOOS, whose main goal was
 to provide methodologies for the reengineering of
 large industrial software systems, we have developed
 the Moose Reengineering Environment, based on the
 language independent FAMIX metamodel. Moose includes
 a metrics engine which supports language independent
 metrics, since coping with software written in
 different implementation languages was one of the
 project''s main constraints. Our current research is
 pushing us towards the development and
 implementation of a metametamodel, which would
 include our metamodel and allow for several
 extension in different research directions, among
 which concept analysis, knowledge management and
 software evolution. In this article we want to
 present our current and future work for the
 transition from language independent to domain
 independent metrics.},
  annote = {internationalworkshop},
  editor = {Fernando Brito e Abreu and Mario Piattini and Geert Poels and Houari A. Sahraoui},
  isbn = {84-699-8696-1},
  keywords = {scg-pub skip-doi stefPub moose kzMetric kzMeta}}

'
)  