examples for tests
Rieg98a
	"self Rieg98a"
^
(CZBibParser parse: 
'

@inproceedings{Rieg98a,
  author = {Matthias Rieger and St\''ephane Ducasse},
  title = {Visual Detection of Duplicated Code},
  booktitle = {Proceedings ECOOP Workshop on Experiences in Object-Oriented Re-Engineering},
  publisher = {Forschungszentrum Informatik Karlsruhe},
  year = {1998},
  url = {http://rmod.inria.fr/archives/papers/Rieg98aEcoopWorkshop.pdf},
  abstract = {Code duplication is considered as bad practice that
 complicates the maintenance and evolution of
 software. Detecting duplicated code is a difficult
 task because of the large amount of data to be
 checked and the fact that a priori it is unknown
 which code part has been duplicated. In this paper,
 we present a tool called DUPLOC that supports code
 duplication detection in a visual and exploratory or
 an automatic way.},
  annote = {internationalworkshop},
  editor = {St\''ephane Ducasse and Joachim Weisbrod},
  keywords = {scg-pub skip-doi kzDuplication},
  number = {6/7/98},
  series = {FZI Report}}

'
)  