generated
reduceTable
^#(
	#(14 0 #reduceFor:) 
	#(15 1 #reduceActionFor___newline___junk___name__1:) 
	#(14 2 #reduceFor:) 
	#(12 1 #reduceFor:) 
	#(22 0 #reduceActionFor_______name___1:) 
	#(17 4 #reduceActionForReferenceCitation1:) 
	#(19 4 #reduceActionForStyleDeclaration1:) 
	#(18 5 #reduceFor:) 
	#(20 5 #reduceActionForDatabaseDeclaration1:) 
	#(22 2 #reduceActionFor_______name___2:) 
	#(21 2 #reduceFor:)
	).