initialize
initializeFrenchEntries
	"self initializeFrenchEntries"
	
	French := Dictionary new.
	French at: InternationalReviewedJournal put: 'Revues internationales avec comit\''e de lecture'.
	French at: TopConferences put: 'Meilleures conf\''erences internationales'.
	French at: NationalReviewedJournal put:  'Revues nationales avec comit\''e de lecture'.
	French at: InternationalConference put: 'Conf\''erences internationales avec comit\''e de lecture'.
	French at: NationalReviewedConference put: 'Conf\''erences nationales avec comit\''e de lecture'.
 	French at: Book put: 'Livres'.
	French at: Booklet put: 'Livrets'.
	French at: HandBook put: 'Tutoriels'.
	French at: BookChapter put: 'Articles dans un ouvrage collectif'.
	French at: InvitedPaper put: 'Articles invit\''es'.
	French at: #editor put: 'Editeur'.
	French at: InternationalReviewedWorkshop put: 'Articles de workshop internationaux avec comit\''e de lecture'.
	French at: NationalWorkshop put: 'Articles de workshop nationaux avec comit\''e de lecture ou de s\''election'.
	French at: PhD put: 'Th\`ese'.
	French at: HDR put: 'Habilitation \''a diriger des recherches'.
	French at: PHDAndHdr put: 'Th\`ese et Habilitation \''a diriger des recherches'.
	French at: Deliverable put: 'Livrables de projets'.
	French at: TechnicalReport put: 'Rapports scientifiques et/ou techniques'.
	French at: ToolDemo put: 'D\''emonstrations d''outils'.
	French at: Periodical put: 'Magazines'.
	French at: Vulgarisation put: 'Articles de vulgarisation'.
	
