initialize
initializeTypes
	"self initializeTypes"
	
	InternationalReviewedJournal := #internationReviewedJournal.
	NationalReviewedJournal := #nationalReviewedJournal.
	TopConferences := #topConferences.
	InternationalConference := #internationalConferences.
	NationalReviewedConference := #nationalConference.
	Book := #book.
	HandBook := #handbook.
	Booklet := #booklet.	
	BookChapter := #bookChapter.
	InvitedPaper := #invitedPapers.
	"Editor := #editor."
	InternationalReviewedWorkshop := #internationalWorkshop.
	NationalWorkshop := #nationalWorkshop.
	PhD := #phd.
	HDR := #hdr.
	PHDAndHdr := #phdAndHdr.
	Deliverable := #deliverable.
	TechnicalReport := #technicalReport.
	ToolDemo := #tooldemo.
	Periodical := #periodical.
	Vulgarisation := #vulgarisation.
	