xhtml
defaultHeaderString
	^ '<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
      <title>', self xhtmlName, '</title>
   </head>
   <body>
      <div id="header">
         <div id="headerSiteTitle">', self xhtmlName, '</div>
         <div id="headerPageTitle">Publications</div>
      </div><!-- header-->
      <div id="mainContent">
	  <div xmlns="" class="paperList"><style type="text/css">
<!--
-->
</style>' withUnixLineEndings 