examples for tests
Abde10a
	"self  Abde10a"
^
(CZBibParser parse: 
'@article{Abde10a,
	Aeres = {ACL},
	Aeresstatus = {aeres12},
	Annote = {internationaljournal},
	Author = {Hani Abdeen and St\''ephane Ducasse and Damien Pollet and Ilham Alloui},
	Doi = {10.1016/j.infsof.2010.07.005},
	Hal-Id = {inria-00531496},
	Impactfactor = {ISI impact factor 1.821 (2010)},
	Inria = {RMOD},
	Inriareport = {2010},
	Journal = {Information and Software Technology Journal},
	Keywords = {moose remoose2 lse-pub cook kzVisualisation},
	Pages = {1312-1330},
	Secondurl = {http://rmod.lille.inria.fr/archives/papers/Abde10a-IST-packageFingerprints.pdf},
	Title = {Package Fingerprint: a visual summary of package interfaces and relationships},
	Url = {http://rmod.lille.inria.fr/archives/papers/Abde10a-IST-Official-packageFingerprints.pdf},
	Volume = {52},
	X-Editorial-Board = {yes},
	X-International-Audience = {yes},
	X-Proceedings = {yes},
	Year = 2010,
	Bdsk-Url-1 = {http://rmod.lille.inria.fr/archives/papers/Abde10a-IST-Official-packageFingerprints.pdf},
	Bdsk-Url-2 = {https://doi.org/10.1016/j.infsof.2010.07.005}}

'
)  
