examples for tests
someArticles
	"self  someArticles"
^
(CZBibParser parse: 
'@article{Abde10a,
	Aeres = {ACL},
	Aeresstatus = {aeres12},
	Annote = {internationaljournal},
	Author = {Hani Abdeen and St\''ephane Ducasse and Damien Pollet and Ilham Alloui},
	Doi = {10.1016/j.infsof.2010.07.005},
	Hal-Id = {inria-00531496},
	Impactfactor = {ISI impact factor 1.821 (2010)},
	Inria = {RMOD},
	Inriareport = {2010},
	Journal = {Information and Software Technology Journal},
	Keywords = {moose remoose2 lse-pub cook kzVisualisation},
	Pages = {1312-1330},
	Secondurl = {http://rmod.lille.inria.fr/archives/papers/Abde10a-IST-packageFingerprints.pdf},
	Title = {Package Fingerprint: a visual summary of package interfaces and relationships},
	Url = {http://rmod.lille.inria.fr/archives/papers/Abde10a-IST-Official-packageFingerprints.pdf},
	Volume = {52},
	X-Editorial-Board = {yes},
	X-International-Audience = {yes},
	X-Proceedings = {yes},
	Year = {2010},
	Bdsk-Url-1 = {http://rmod.lille.inria.fr/archives/papers/Abde10a-IST-Official-packageFingerprints.pdf},
	Bdsk-Url-2 = {https://doi.org/10.1016/j.infsof.2010.07.005}}


@inproceedings{Denk08b,
  Annote       = {internationalconference},
  Author       = {Marcus Denker and Mathieu Suen and St\''ephane
                  Ducasse},
  Booktitle    = {Proceedings of TOOLS EUROPE 2008},
  peer	       = {yes},
  pages	       = {218--237},
  aeres	       = {ACT},
  aeresstatus  = {aeres12},
  inria	       = {RMOD},
  selectif     = {non},
  ISSN	       = {1865-1348},
  Keywords     = {scg-pub jb08 fb08 snf08 reflectivity},
  labo 		= {dans},
  Publisher    = {Springer-Verlag},
  Series       = {LNBIP},
  Volume       = 11,
  Doi	       = {10.1007/978-3-540-69824-1_13},
  Url	       = {http://scg.unibe.ch/archive/papers/Denk08bMetaContextLNBIP.pdf},
  Title	       = {The Meta in Meta-object Architectures},
  hal          = {inria-00271286,p56w09p},
  Year	       = {2008}
}

@inproceedings{Chev11a,
	author = {Chevalier-Boisvert, Maxime and Lavoie, Erick and Feeley, Marc and Dufour, Bruno},
	booktitle = {Dynamic Language Symposium},
	title = {Bootstrapping a Self-Hosted Research Virtual Machine for JavaScript},
	year = {2011}
}

@article{Duca10a,
author = {St\''ephane Ducasse and Damien Pollet},
keywords = {insubmission},
title = {Fingerprints},
journal = {Journal of Information System},
year = {2010}
}

@inproceedings{Abde08a,
author = {Hani Abdeen and Ilham Alloui and St\''ephane Ducasse and Damien Pollet and Mathieu Suen},
title = {Package Reference Fingerprint: a Rich and Compact Visualization to Understand Package Relationships},
booktitle = {European Conference on Software Maintenance and Reengineering (CSMR)},
pages = {213--222},
publisher = {IEEE Computer Society Press},
year = {2008},
acceptnum = {24},
accepttotal = {87}
}


@article{Duca12a,
     author = {St\''ephane Ducasse and Zork Ranger},
	annote = {internationaljournal},
     title = {Woa},
     journal = {Journal of Information System},
     Url	       = {obsoleteData.pdf},
     year = {2010}
}

'
)  
