generated
reduceTable
^#(
	#(16 0 #reduceActionFor__CommentDeclaration_MacroDeclaration_EntryDeclaration__1:) 
	#(31 1 #reduceActionForBibfile1:) 
	#(21 0 #reduceActionFor__CommentDeclaration_MacroDeclaration_EntryDeclaration__1:) 
	#(16 2 #reduceActionFor__CommentDeclaration_MacroDeclaration_EntryDeclaration__2:) 
	#(14 1 #reduceActionFor__CommentDeclaration_MacroDeclaration_EntryDeclaration_2:) 
	#(27 2 #reduceActionForBodyContents1:) 
	#(17 1 #reduceActionFor__CommentDeclaration_MacroDeclaration_EntryDeclaration_2:) 
	#(18 2 #buildMacro:) 
	#(19 2 #nil) 
	#(21 2 #reduceActionFor__CommentDeclaration_MacroDeclaration_EntryDeclaration__2:) 
	#(23 1 #reduceActionForSimpleValue3:) 
	#(23 1 #reduceActionForSimpleValue4:) 
	#(23 1 #reduceActionForSimpleValue1:) 
	#(26 3 #reduceActionForField1:) 
	#(25 0 #reduceActionFor__CommentDeclaration_MacroDeclaration_EntryDeclaration__1:) 
	#(30 3 #buildEntry:) 
	#(20 2 #reduceFor:) 
	#(22 2 #reduceActionForValue1:) 
	#(25 2 #reduceActionFor__CommentDeclaration_MacroDeclaration_EntryDeclaration__2:) 
	#(24 2 #reduceFor:)
	).