generated
reduceTable
^#(
	#(16 1 #reduceActionFor_name__1:) 
	#(5 0 #reduceActionFor___and__author__1:) 
	#(13 0 #nil) 
	#(6 2 #reduceActionForauthorList1:) 
	#(16 2 #reduceActionFor_name__2:) 
	#(13 1 #reduceActionFor_______name__________name______2:) 
	#(8 2 #buildAuthor:) 
	#(5 2 #reduceActionFor_name__2:) 
	#(11 0 #nil) 
	#(9 2 #reduceFor:) 
	#(11 1 #reduceActionFor_______name__________name______2:) 
	#(12 3 #reduceFor:) 
	#(10 2 #reduceFor:)
	).