generated-tables
reduceTable
	^#(
#(5 0 #reduceActionForRepeatXXGroupXXXXXXandXXauthor1:)
#(5 2 #reduceActionForRepeatXXGroupXXXXXXandXXauthor2:)
#(6 2 #reduceActionForauthorList1:)
#(7 3 #buildAuthor:)
#(8 2 #reduceFor:)
#(9 1 #reduceActionForRepeatXMultipleXXXnameX1:)
#(9 2 #reduceActionForRepeatXMultipleXXXnameX2:)
#(10 2 #reduceFor:)
#(11 0 #reduceActionForOptionalXXGroupXXXXXXXXXRepeatXMultipleXXXnameX1:)
#(11 1 #reduceActionForOptionalXXGroupXXXXXXXXXRepeatXMultipleXXXnameX2:)
#(14 1 #reduceFor:)
)