SystemOrganization addCategory: #'Citezen-Reborn'!
SystemOrganization addCategory: #'Citezen-Reborn-Core-Visitor'!
SystemOrganization addCategory: #'Citezen-Reborn-DocModel'!
SystemOrganization addCategory: #'Citezen-Reborn-DocumentBuilder'!
SystemOrganization addCategory: #'Citezen-Reborn-FormattingVisitors'!
SystemOrganization addCategory: #'Citezen-Reborn-Manifest'!
SystemOrganization addCategory: #'Citezen-Reborn-Pillar'!
SystemOrganization addCategory: #'Citezen-Reborn-Tests'!
