initialization
initialize
	"self initialize"
	
	Article := #article. 
	Book := #book. 
	Booklet := #booklet. 
	Conference := #conference.
	Editor := #editor. 
	InBook := #inbox. 
	InCollection := #incollection. 
	InProceedings :=#inproceedings. 
	Manual := #manual. 
	MastersThesis := #masterthesis. 
	PhDThesis := #phdthesis. 
	Proceedings := #proceedings. 
	TechReport :=  #techreport.
	Unpublished := #unpublished.
	Misc := #misc