as yet unclassified
xmlHeaderString
	^ '<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<link rel="stylesheet" href="CSS/Stef.css"/>
     <title>', self xhtmlName, '</title>
   </head>
   <body>
<div id="header">
<div id="headerSideTitle">
St&eacute;phane Ducasse</div>    <!--Closing headerSideTitle --><div id="headerPageTitle">
Publications</div>    <!--Closing headerPageTitle --></div>    <!--Closing header --><div id="menu">
<div id="toc">
<div id="tocItem">
<a href="index.html">Home</a></div>    <!--Closing tocItem -->
<div id="tocItem">
<a href="http://www.pharo-project.org">Pharo</a></div>    <!--Closing tocItem -->
<div id="tocItem">
<a href="Publications.html">Publications</a></div>    <!--Closing tocItem -->
<div id="tocItem">
<a href="Books.html">Books</a></div>    <!--Closing tocItem -->
<div id="tocItem">
<a href="FreeBooks.html">Free Smalltalk Books</a></div>    <!--Closing tocItem -->
<div id="tocItem">
<a href="Resources.html">Downloads/Resources</a></div>    <!--Closing tocItem -->
<div id="tocItem">
<a href="Teaching.html">Lectures and Presentations</a></div>    <!--Closing tocItem -->
<div id="tocItem">
<a href="Coordinates.html">Coordinates</a></div>    <!--Closing tocItem --></div>    <!--Closing toc --></div>    <!--Closing menu --><div id="mainContent">
<div id="personalDetails">
<div>
<img src="StefFingerOnNose128.jpg">
</div>
<div id="personalDetailsItem">
<a href="http://www.inria.fr/">INRIA</a></div>    <!--Closing personalDetailsItem -->
<div id="personalDetailsItem">
<a href="http://rmod.lille.inria.fr/">RMOD</a></div>    <!--Closing personalDetailsItem -->
<div id="personalDetailsItem">
<a href="mailto:stephane.ducasse@inria.fr">Stephane.Ducasse(@At@)inria.fr</a></div>    <!--Closing personalDetailsItem --></div>    <!--Closing personalDetails -->' withUnixLineEndings 