testing
testSeveral
	super testSeveral.
	self assert: result =  '\bibitem[displayKey]{Duca10a}
St\''ephane Ducasse and Damien Pollet. 
\newblock Fingerprints. 
\newblock In Journal of Information System, 2010.

\bibitem[displayKey]{Abde08a}
Hani Abdeen, Ilham Alloui, St\''ephane Ducasse, Damien Pollet, and Mathieu Suen. 
\newblock Package Reference Fingerprint: a Rich and Compact Visualization to Understand Package Relationships. 
\newblock In European Conference on Software Maintenance and Reengineering (CSMR), p. 213--222, IEEE Computer Society Press, 2008. Acceptance rate: 24/87 = 28%.

' 