builder
notTeamEntry
^
(CZBibParser parse: 
'@article{Desm08a,
	author = {Desmet, Lieven and Verbaeten, Petrus and Joosen, Wouter and Piessens, Frank},
	title = {Provable protection against web application vulnerabilities related to session data dependencies},
	journal = {IEEE transactions on software engineering},
	year = {2008},
	month = jan,
	volume = {34},
	number = {1},
	pages = {50--64},
	url = {https://lirias.kuleuven.be/handle/123456789/161855},
	doi = {10.1109/TSE.2007.70742},
	issn = {0098-5589}
}') entries first