metadata
privateFields
	"privateFields is used to determine the fields that should be removed from our extended bib to offer a public bib"
	"Would be probably better to say that private is everything that is not public"
	
	^ #(hal keywords annote aeresstatus aeres selectif labo inria rate #'x-editorial-board' #'x-proceedings' #'x-international-audience' #'x-pays' #'x-invited-conference' #'x-scientific-popularization' #'x-language'  #'peerreview' #'hal-id' #Cvs)