team 
teamMemberPatterns
	^ teamMemberPatterns
		ifNil:
			[ teamMemberPatterns := #('*Ducasse*S*' '*S*Ducasse*' '*Denker*' '*Auverlot*' '*Anquetil*' '*Costiou*' '*Aranega*' '*Govin*' '*Pollet*' '*Abdeen*' '*Laval*' '*Marr*' '*Hora*' '*Etien*' '*Blondeau*' '*Casaccio*' '*Bruni*' '*Tesone*' '*Teruel*' '*Polito*' '*Martinez*Peck*' '*Uquillas*' '*Arnaud*' '*Bhatti*U*' '*Fernandes*' '*Razavizadeh*' '*Uquilla*' '*Dias*' '*Cassou*' '*Ryseghem*' '*Papoulias*' '*Demarey*' '*Bera*' '*Miranda*') ]